# Generated by Django 4.0.5 on 2022-06-22 17:46

import base.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('item_quantity', models.FloatField()),
                ('item_price', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Customer Name', max_length=30)),
                ('address', models.CharField(help_text="Enter customer's Address", max_length=250)),
                ('items', djongo.models.fields.ArrayField(model_container=base.models.Item, null=True)),
            ],
        ),
    ]
